// THE ONE USER ENTITY.
//
// There is no separate member entity. Everyone in the mess - admin, president,
// manager and member - is a user record in users.json, and `member_id` is the
// business identifier that only a member carries.
//
//   id        immutable internal identifier, generated by the app
//   member_id business identifier for members, null for every other role
//
// A field that does not apply to a person is stored as null rather than being
// omitted, so every record has the same shape.

export type Role = "admin" | "manager" | "president" | "member";

export type EntryFeeStatus = "paid" | "pending";

export type User = {
  id: string;
  member_id: string | null;
  name: string;
  email: string;
  /** Hashed on the server. Never sent to a client and never editable here. */
  password: string;
  mobile: string | null;
  address: string | null;
  room: string | null;
  joiningDate: string | null;
  /** true = active, false = inactive. */
  status: boolean;
  role: Role;
  wallet_id: number | null;
  deposite_amount: number | null;
  entryFee: number | null;
  entryFeeStatus: EntryFeeStatus | null;
  entryFeePaidDate: string | null;
  image_url: string | null;
  login_status: boolean;
  login_at: string | null;
  logout_at: string | null;
};

/**
 * A user as the browser is allowed to see it: the unified record with the
 * password removed. Everything else, including the member fields, is intact.
 */
export type PublicUser = Omit<User, "password">;

/** True for the roles that may reach the admin panel. */
export const isStaffRole = (role: Role) => role !== "member";
